core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('network.urls', namespace='network')),
    path('', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

network/urls.py
from django.urls import path
from . import views


app_name = 'network'

urlpatterns = [
    path('', views.home, name='home'),
    path('post_detail/<uuid:post_id>', views.post_detail, name='post_detail'),
    path('like/', views.like, name='like'),
    path('comment/', views.comment, name='comment'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/<slug:slug>', views.user_detail, name='user_detail'),
    path("follow/<slug:slug>", views.follow, name='follow'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
]

templates/base.html
<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />
  <!-- Static Files -->
  {% load static %}
  <!-- JQuery -->
  <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
</head>

<body>
  {% include "user/login.html" %}
  <header>
    <nav class="navbar shadow navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img
            src="https://cdn.iconscout.com/icon/free/png-256/network-nodes-connection-sharing-social-media-1-9592.png"
            class="me-2" height="40" alt="" loading="lazy" />
          <small>My Network</small>
        </a>

        <div class="d-flex align-items-center me-3">
          {% if user.is_authenticated %}
          <a href={% url 'users:profile' %}>
            <img src={{ user.profile_pic.url }} class="rounded-circle" height="30" width='30' alt="" loading="lazy" />
          </a>
          {% else %}
          <button type="button" class="btn btn-primary" data-mdb-toggle='modal' data-mdb-target='#loginModal'>
            Iniciar Sesión
          </button>
          {% endif %}
        </div>
      </div>

      </div>
    </nav>
  </header>

  {% for message in messages %}
  <div class="alert alert-{{message.tags}} alert-dismissible fade show" role='alert'>
    {{ message }}
  </div>
  {% endfor %}

  <div class="d-flex center" id="content">{% block content %} {% endblock %}</div>

</body>

<!-- MDB -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>

<script>
  $(document).on('click', '.like-button', function (e) {
    e.preventDefault();
    var post_id = $(this).data('post');
    $.ajax({
      type: 'GET',
      url: '{% url "network:like" %}',
      data: {
        post_id: post_id
      },
      success: function (response) {
        $('#' + post_id).load(location.href + ' #' + post_id)
      },
      error: function (xhr, errmsg, err) {}
    });
  })
  
  $(document).on('click', '.comment-button', function (e) {
    e.preventDefault();
    var post_id = $(this).data('post');
    var comment = $('#comment' + post_id).prop('value')
    if (comment != '') {
      $.ajax({
        type: 'GET',
        url: '{% url "network:comment" %}',
        data: {
          post_id: post_id,
          comment: comment
        },
        success: function (response) {
          $(".comment-div").load(location.href + " .comment-div")
          $("#comment_form")[0].reset()
        },
        error: function (xhr, errmsg, err) {}
      });
    }
  })
</script>
</html>

templates/home.html
{% extends "./base.html" %}

{% block content %}

<div class='container col-md-8 col-xl-6'>
  <h2 class='text-center my-4'>Últimas Publicaciones</h2>

  {% for post in posts %}

  <div class="card shadow border mb-3 p-4">
    <a href={{ post.get_absolute_url }}>
      <img src = "{{post.image.url}}" class = "card-img-top m-0" / >
    </a>

    <div class="border-0 p-0 d-flex">
      <div class="col-8">
        <a href={{ post.author.get_absolute_url }}>
          <h4 class="m-0"> {{post.author}}</h4>
        </a>
        <p class="mb-1">
          {{post.description}}
        </p>
      </div>
      
      <div id="{{ post.identifier }}"class='d-flex justify-content-end col-4 p-0'>
        <a
          type="button"
          data-post="{{post.identifier}}"
          class="fs-5 text-reset like-button"
          >
          {% if user in post.likes.all %}
          <i class="fas fa-heart text-danger"></i>
          {% else%}
          <i class="far fa-heart"></i>
          {% endif %}
        </a>
        <p class="fw-bold fs-5 px-1">{{post.likes.all | length}}</p>
        <p class="fw-bold fs-5 col-auto">Me gusta</p>
      </div>

    </div>

    <hr class="mt-0"/>

    <div class="mb-1 comment-div border-0">
      {% for comment in post.get_comments %}
      <p class="mb-0">
        <strong>{{ comment.user }}</strong> {{ comment.body }}
      </p>
      {% endfor %}
    </div>
    
    <hr />
    <div class="card-footer border-0 py-0">
      <p class="card-text"><small class="text-muted"> {{post.published}} </small></p>
    </div>
  </div>
  {% endfor %}

</div>

{% endblock %}

templates/post_detail.html
{% extends "./base.html" %} {% block content %}
<div class="container col-md-8 col-xl-6 my-4 p-4 border shadow ">
  <img src = "{{post.image.url}}" class = "card-img-top m-0" / >
  <div class="border-0 p-0 d-flex">
    <div class="col-9">
      <p class="mb-1">
        <h4 class="m-0"> {{post.author}}</h4> {{post.description}}
      </p>
    </div>
    
    <div id="{{ post.identifier }}"class='d-flex justify-content-end col-3 p-0'>
      <a
        type="button"
        data-post="{{post.identifier}}"
        class="fs-5 text-reset like-button"
        >
        {% if user in post.likes.all %}
        <i class="fas fa-heart text-danger"></i>
        {% else%}
        <i class="far fa-heart"></i>
        {% endif %}
      </a>
      <p class="fw-bold fs-5 px-1">{{post.likes.all | length}}</p>
      <p class="fw-bold fs-5 col-md-auto">Me gusta</p>

    </div>
  </div>

  <hr class="mt-0"/>

  <div class="mb-1 row comment-div border-0">
    {% for comment in post.get_comments %}
    <p class="mb-0">
      <strong>{{ comment.user }}</strong> {{ comment.body }}
    </p>
    {% endfor %}
  </div>

  <hr clas='border-0'/>
  <form class="row" id="comment_form">
    <div class="d-flex justify-content-center">
      <img
        src="{{user.profile_pic.url}}"
        class="mx-2 rounded-circle my-auto"
        height="20"
        width="20"
        alt=""
        loading="lazy"
      />
      <input
        id="comment{{post.identifier}}"
        class="form-control  my-auto mx-2"
        placeholder="Añadir un comentario..."
      />
      <div>
        <button
          class="btn btn-primary btn-sm my-auto btn-block border comment-button"
          data-post="{{post.identifier}}"
          type="submit"
        >
          Publicar
        </button>
      </div>
    </div>
  </form>
  <hr />
  <div class="card-footer border-0 py-0">
    <p class="card-text"><small class="text-muted"> {{post.published}} </small></p>
  </div>
</div>